M48
; DRILL file {KiCad 9.0.5-9.0.5~ubuntu25.04.1} date 2025-10-12T20:46:30+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-12T20:46:30+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5-9.0.5~ubuntu25.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
%
G90
G05
T1
X137.4Y-148.327
X141.8Y-148.327
M30
